---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-monitoring  
  namespace: cattle-monitoring-system
spec:
  interval: 5m
  chart:
    spec:  
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rancher-monitoring-crd
      version: 100.0.0+up16.6.0
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system  