apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: wireguard
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:    
    matchLabels:
      app: 'wireguard-exporter'
  podMetricsEndpoints:
    - targetPort: http-metrics
