---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: rancher
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
  values:
    replicas: 2
    hostname: "rancher.${SECRET_DOMAIN}"    
    ingress:
      tls:
        source: secret