---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-cert
spec:
  commonName: rwcloud
  isCA: true
  issuerRef:
    kind: Issuer
    name: my-issuer
  secretName: elastic-cert
  subject:
    organizations:
      - rwcloud
