defaultNamespace: elastic
helm:
  releaseName: kibana
  chart: kibana
  repo: https://helm.elastic.co
  version: 7.15.0
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.rwcloud.org/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.rwcloud.org/oauth2/start
      hosts:
        - host: kibana.rwcloud.org
          paths:
            - path: /
      tls:
        - secretName: chart-example-tls
          hosts:
            - kibana.rwcloud.org
