defaultNamespace: longhorn-system
helm:
  releaseName: longhorn
  chart: longhorn
  repo: https://charts.rancher.io
  version: 100.1.0+up1.2.2
  values:
    defaultSettings:      
      backupTarget: 's3://longhorn@us-east-1/'
      backupTargetCredentialSecret: minio-secrets
      defaultReplicaCount: 2
    resources:   
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
dependsOn:
  - name: longhorn-fleet-infra-longhorn-longhorn-crd