---
- name: stop fail2ban
  service:
    name: fail2ban
    state: stopped

- import_tasks: install.yml

- import_tasks: service.yml

- import_tasks: config.yml

- import_tasks: manage.yml

- name: start fail2ban
  service:
    name: fail2ban
    state: started