---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nobackup-1replica
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
