---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nobackup
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
