---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.7.5
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  values:
    monitoring:
      enabled: true

    dashboard:
      enabled: true
    
    ingress:
      dashboard: 
        # annotations:
        #   kubernetes.io/ingress.class: nginx
        #   external-dns.alpha.kubernetes.io/hostname: example.com
        #   nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
        host:
          name: rook.${SECRET_DOMAIN}
          path: "/ceph-dashboard(/|$)(.*)"
        tls:
          hosts: 
            - rook.${SECRET_DOMAIN}

    cephBlockPools: {}
    cephFileSystems: {}
    cephObjectStores: {}