---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:  
    spec:      
      chart: longhorn
      version: 100.1.0+up1.2.2
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      interval: 5m 
  dependsOn:
    - name: longhorn-crd
  values:
    defaultSettings:      
      backupTarget: 's3://longhorn@us-east-1/'
      backupTargetCredentialSecret: minio-secrets
      defaultReplicaCount: 2
      guaranteedEngineManagerCPU: 5
      guaranteedReplicaManagerCPU: 5
    resources:   
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi