---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-crd
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn-crd
      version: 100.1.0+up1.2.2
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      interval: 5m 