---
# tasks file for ronnywalter.fail2ban
- name: Install fail2ban.
  apt:
    name: fail2ban
    state: present

- name: Install whois
  apt:
    name: whois
    state: present

- name: Configuring /etc/fail2ban/jail.d/defaults-debian.conf
  template:
    src: sshd.jail.j2
    dest: /etc/fail2ban/jail.d/defaults-debian.conf
    owner: root
    group: root
    mode: '644'

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban
    state: restarted
    enabled: true