apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wildcard-certificate
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-issuer
  interval: 5m
  path: "./deployments/infrastructure/certificates/wildcard"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    #- kind: ConfigMap
    #  name: cluster-settings
    - kind: Secret
      name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rancher-certificate
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-issuer
  interval: 5m
  path: "./deployments/infrastructure/certificates/rancher"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    #- kind: ConfigMap
    #  name: cluster-settings
    - kind: Secret
      name: cluster-secrets