apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: wildcard-certificate
  interval: 5m
  path: "./deployments/infrastructure/ingress-nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    #- kind: ConfigMap
    #  name: cluster-settings
    - kind: Secret
      name: cluster-secrets
