apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  path: "./deployments/infrastructure/storage/longhorn"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
    #- kind: ConfigMap
    #  name: cluster-settings
    - kind: Secret
      name: cluster-secrets
