defaultNamespace: elastic
helm:
  releaseName: elasticsearch
  chart: elasticsearch
  repo: https://helm.elastic.co
  version: 7.15.0
  values:
    esConfig: 
      elasticsearch.yml: |
        xpack.monitoring.collection.enabled: true
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 15Gi
      storageClassName: longhorn-nobackup
dependsOn:
  - name: longhorn-fleet-infra-longhorn-longhorn-deployment