apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata: 
  name: clusteroutput-all
  namespace: cattle-logging-system  
spec:
  elasticsearch:
    buffer:
      chunk_limit_size: 256M
      flush_interval: 5s
      flush_mode: interval
      flush_thread_count: 1
      overflow_action: drop_oldest_chunk
      retry_forever: true
      retry_max_interval: 60s
      retry_type: exponential_backoff
      total_limit_size: 5G
      type: file    
    customize_template: '{"index_pattern_name": "rwcloud-logs-all"}'
    enable_ilm: true
    hosts: elasticsearch-es-http.logging.svc.cluster.local:9200
    ilm_policy: '{ "policy" : { "phases" : { "hot" : { "min_age" : "0ms", "actions"
      : { "rollover" : { "max_age" : "1d" }, "set_priority" : { "priority" : 50 }
      } }, "delete" : { "min_age" : "7d", "actions" : { "delete" : { } } }, "warm"
      : { "min_age" : "0ms", "actions" : { "allocate" : { "number_of_replicas" : 0,
      "include" : { }, "exclude" : { }, "require" : { } }, "readonly" : { }, "set_priority"
      : { "priority" : 25 } } } } } }'
    ilm_policy_id: rwcloud-ilm-logs-all
    ilm_policy_overwrite: true
    include_tag_key: true
    include_timestamp: true
    index_date_pattern: now/d
    index_name: rwcloud-logs-all
    log_es_400_reason: true
    logstash_format: false
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elastic-password-secret
    request_timeout: 10s
    rollover_index: false
    scheme: https
    ssl_verify: false
    suppress_type_name: true
    template_file:
      mountFrom:
        secretKeyRef:
          key: default-index-template
          name: index-templates
    template_name: rwcloud-logs-all
    template_overwrite: true
    user: ronny
status:
  active: true
