---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: traefik
      version: 10.6.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      kind: DaemonSet
    hostNetwork: true
    service:
      type: ClusterIP
    ports:
      traefik:
        host
      web:
        port: 80
        hostPort: 80       
        redirectTo: websecure        
      websecure:
        port: 443
        hostPort: 443
            