---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: traefik
      version: 10.6.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      kind: DaemonSet
    hostNetwork: true
    service:
      type: ClusterIP
    ports:
      web:
        port: 80        
        redirectTo: websecure        
      websecure:
        port: 443
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json    
    ingressRoute:
      dashboard:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1