- name: Prepare hosts
  hosts: all
  vars:
    rke2_version: v1.21.5+rke2r1
  roles:
     - ronnywalter.common
     - ronnywalter.resolv_nodes
     - ronnywalter.ipv6
     - githubixx.ansible_role_wireguard
     - ronnywalter.fail2ban
     - weareinteractive.ufw  

- name: Prepare rancher-cluster
  hosts: rancher_nodes
  vars:
    rke2_version: v1.21.5+rke2r1
    rke2_custom_manifests: manifests/
    rke2_token: ljkhfewiu32ni439
  roles:     
     - ronnywalter.prepare_rke2
     

- name: Prepare workload-cluster
  serial: 1
  hosts: nodes
  vars:
    rke2_version: v1.21.5+rke2r1
    rke2_custom_manifests: manifests/
    rke2_token: ljkhfewiu32ni439
  roles:     
     - ronnywalter.prepare_rke2