---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: minio-operator
      version: 4.2.14
      sourceRef:
        kind: HelmRepository
        name: minio-operator-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      labels: {}
      annotations: 
        nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
      tls: 
        minio.${SECRET_DOMAIN}
      host: minio.${SECRET_DOMAIN}
      path: /